#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 73
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 49
#define ALIAS_COUNT 6
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 11
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 9

enum ts_symbol_identifiers {
  anon_sym_BANG = 1,
  anon_sym_LBRACE = 2,
  anon_sym_RBRACE = 3,
  anon_sym_AMP = 4,
  anon_sym_EQ = 5,
  aux_sym_set_delimiter_statement_token1 = 6,
  anon_sym_GT = 7,
  anon_sym_SLASH = 8,
  anon_sym_POUND = 9,
  anon_sym_CARET = 10,
  anon_sym_LT = 11,
  anon_sym_DOLLAR = 12,
  anon_sym_DOT = 13,
  sym__start_tag_name = 14,
  sym__end_tag_name = 15,
  sym__erroneous_end_tag_name = 16,
  sym_start_delimiter = 17,
  sym_end_delimiter = 18,
  sym__comment_content = 19,
  sym__identifier_content = 20,
  sym__set_start_delimiter_content = 21,
  sym__set_end_delimiter_content = 22,
  sym__old_end_delimiter = 23,
  sym_text = 24,
  sym_template = 25,
  sym__declaration = 26,
  sym_comment_statement = 27,
  sym__statement = 28,
  sym_interpolation_statement = 29,
  sym_triple_statement = 30,
  sym_ampersand_statement = 31,
  sym_set_delimiter_statement = 32,
  sym_partial_statement = 33,
  sym_section = 34,
  sym__section_end = 35,
  sym_section_begin = 36,
  sym_inverted_section = 37,
  sym_inverted_section_begin = 38,
  sym_inheritance_statement = 39,
  sym_inheritance_begin = 40,
  sym_block_statement = 41,
  sym_block_begin = 42,
  sym__expression = 43,
  sym_identifier = 44,
  sym_path_expression = 45,
  aux_sym_template_repeat1 = 46,
  aux_sym_section_repeat1 = 47,
  aux_sym_path_expression_repeat1 = 48,
  alias_sym__end_delimiter = 49,
  alias_sym__start_delimiter = 50,
  alias_sym_block_end = 51,
  alias_sym_inheritance_end = 52,
  alias_sym_inverted_section_end = 53,
  alias_sym_partial_content = 54,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_BANG] = "!",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_AMP] = "&",
  [anon_sym_EQ] = "=",
  [aux_sym_set_delimiter_statement_token1] = "set_delimiter_statement_token1",
  [anon_sym_GT] = ">",
  [anon_sym_SLASH] = "/",
  [anon_sym_POUND] = "#",
  [anon_sym_CARET] = "^",
  [anon_sym_LT] = "<",
  [anon_sym_DOLLAR] = "$",
  [anon_sym_DOT] = ".",
  [sym__start_tag_name] = "tag_name",
  [sym__end_tag_name] = "tag_name",
  [sym__erroneous_end_tag_name] = "erroneous_tag_name",
  [sym_start_delimiter] = "start_delimiter",
  [sym_end_delimiter] = "end_delimiter",
  [sym__comment_content] = "_comment_content",
  [sym__identifier_content] = "_identifier_content",
  [sym__set_start_delimiter_content] = "_set_start_delimiter_content",
  [sym__set_end_delimiter_content] = "_set_end_delimiter_content",
  [sym__old_end_delimiter] = "end_delimiter",
  [sym_text] = "text",
  [sym_template] = "template",
  [sym__declaration] = "_declaration",
  [sym_comment_statement] = "comment_statement",
  [sym__statement] = "_statement",
  [sym_interpolation_statement] = "interpolation_statement",
  [sym_triple_statement] = "triple_statement",
  [sym_ampersand_statement] = "ampersand_statement",
  [sym_set_delimiter_statement] = "set_delimiter_statement",
  [sym_partial_statement] = "partial_statement",
  [sym_section] = "section",
  [sym__section_end] = "section_end",
  [sym_section_begin] = "section_begin",
  [sym_inverted_section] = "inverted_section",
  [sym_inverted_section_begin] = "inverted_section_begin",
  [sym_inheritance_statement] = "inheritance_statement",
  [sym_inheritance_begin] = "inheritance_begin",
  [sym_block_statement] = "block_statement",
  [sym_block_begin] = "block_begin",
  [sym__expression] = "_expression",
  [sym_identifier] = "identifier",
  [sym_path_expression] = "path_expression",
  [aux_sym_template_repeat1] = "template_repeat1",
  [aux_sym_section_repeat1] = "section_repeat1",
  [aux_sym_path_expression_repeat1] = "path_expression_repeat1",
  [alias_sym__end_delimiter] = "_end_delimiter",
  [alias_sym__start_delimiter] = "_start_delimiter",
  [alias_sym_block_end] = "block_end",
  [alias_sym_inheritance_end] = "inheritance_end",
  [alias_sym_inverted_section_end] = "inverted_section_end",
  [alias_sym_partial_content] = "partial_content",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_EQ] = anon_sym_EQ,
  [aux_sym_set_delimiter_statement_token1] = aux_sym_set_delimiter_statement_token1,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_CARET] = anon_sym_CARET,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym__start_tag_name] = sym__start_tag_name,
  [sym__end_tag_name] = sym__start_tag_name,
  [sym__erroneous_end_tag_name] = sym__erroneous_end_tag_name,
  [sym_start_delimiter] = sym_start_delimiter,
  [sym_end_delimiter] = sym_end_delimiter,
  [sym__comment_content] = sym__comment_content,
  [sym__identifier_content] = sym__identifier_content,
  [sym__set_start_delimiter_content] = sym__set_start_delimiter_content,
  [sym__set_end_delimiter_content] = sym__set_end_delimiter_content,
  [sym__old_end_delimiter] = sym_end_delimiter,
  [sym_text] = sym_text,
  [sym_template] = sym_template,
  [sym__declaration] = sym__declaration,
  [sym_comment_statement] = sym_comment_statement,
  [sym__statement] = sym__statement,
  [sym_interpolation_statement] = sym_interpolation_statement,
  [sym_triple_statement] = sym_triple_statement,
  [sym_ampersand_statement] = sym_ampersand_statement,
  [sym_set_delimiter_statement] = sym_set_delimiter_statement,
  [sym_partial_statement] = sym_partial_statement,
  [sym_section] = sym_section,
  [sym__section_end] = sym__section_end,
  [sym_section_begin] = sym_section_begin,
  [sym_inverted_section] = sym_inverted_section,
  [sym_inverted_section_begin] = sym_inverted_section_begin,
  [sym_inheritance_statement] = sym_inheritance_statement,
  [sym_inheritance_begin] = sym_inheritance_begin,
  [sym_block_statement] = sym_block_statement,
  [sym_block_begin] = sym_block_begin,
  [sym__expression] = sym__expression,
  [sym_identifier] = sym_identifier,
  [sym_path_expression] = sym_path_expression,
  [aux_sym_template_repeat1] = aux_sym_template_repeat1,
  [aux_sym_section_repeat1] = aux_sym_section_repeat1,
  [aux_sym_path_expression_repeat1] = aux_sym_path_expression_repeat1,
  [alias_sym__end_delimiter] = alias_sym__end_delimiter,
  [alias_sym__start_delimiter] = alias_sym__start_delimiter,
  [alias_sym_block_end] = alias_sym_block_end,
  [alias_sym_inheritance_end] = alias_sym_inheritance_end,
  [alias_sym_inverted_section_end] = alias_sym_inverted_section_end,
  [alias_sym_partial_content] = alias_sym_partial_content,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_set_delimiter_statement_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym__start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__erroneous_end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_start_delimiter] = {
    .visible = true,
    .named = true,
  },
  [sym_end_delimiter] = {
    .visible = true,
    .named = true,
  },
  [sym__comment_content] = {
    .visible = false,
    .named = true,
  },
  [sym__identifier_content] = {
    .visible = false,
    .named = true,
  },
  [sym__set_start_delimiter_content] = {
    .visible = false,
    .named = true,
  },
  [sym__set_end_delimiter_content] = {
    .visible = false,
    .named = true,
  },
  [sym__old_end_delimiter] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_template] = {
    .visible = true,
    .named = true,
  },
  [sym__declaration] = {
    .visible = false,
    .named = true,
  },
  [sym_comment_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_interpolation_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_triple_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_ampersand_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_set_delimiter_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_partial_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_section] = {
    .visible = true,
    .named = true,
  },
  [sym__section_end] = {
    .visible = true,
    .named = true,
  },
  [sym_section_begin] = {
    .visible = true,
    .named = true,
  },
  [sym_inverted_section] = {
    .visible = true,
    .named = true,
  },
  [sym_inverted_section_begin] = {
    .visible = true,
    .named = true,
  },
  [sym_inheritance_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_inheritance_begin] = {
    .visible = true,
    .named = true,
  },
  [sym_block_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_block_begin] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_path_expression] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_template_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_section_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_path_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym__end_delimiter] = {
    .visible = true,
    .named = true,
  },
  [alias_sym__start_delimiter] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_block_end] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_inheritance_end] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_inverted_section_end] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_partial_content] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [1] = alias_sym_inverted_section_end,
  },
  [2] = {
    [1] = alias_sym_inheritance_end,
  },
  [3] = {
    [1] = alias_sym_block_end,
  },
  [4] = {
    [2] = alias_sym_inverted_section_end,
  },
  [5] = {
    [2] = alias_sym_inheritance_end,
  },
  [6] = {
    [2] = alias_sym_block_end,
  },
  [7] = {
    [0] = alias_sym__start_delimiter,
    [3] = alias_sym__end_delimiter,
  },
  [8] = {
    [2] = alias_sym_partial_content,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  sym__section_end, 4,
    sym__section_end,
    alias_sym_block_end,
    alias_sym_inheritance_end,
    alias_sym_inverted_section_end,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 21,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 23,
  [34] = 34,
  [35] = 18,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 39,
  [47] = 43,
  [48] = 45,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(1);
      ADVANCE_MAP(
        '!', 2,
        '#', 10,
        '$', 13,
        '&', 5,
        '.', 14,
        '/', 9,
        '<', 12,
        '=', 6,
        '>', 8,
        '^', 11,
        '{', 3,
        '}', 4,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(7);
      END_STATE();
    case 1:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(aux_sym_set_delimiter_statement_token1);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_CARET);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 2},
  [2] = {.lex_state = 0, .external_lex_state = 2},
  [3] = {.lex_state = 0, .external_lex_state = 2},
  [4] = {.lex_state = 0, .external_lex_state = 2},
  [5] = {.lex_state = 0, .external_lex_state = 2},
  [6] = {.lex_state = 0, .external_lex_state = 2},
  [7] = {.lex_state = 0, .external_lex_state = 2},
  [8] = {.lex_state = 0, .external_lex_state = 2},
  [9] = {.lex_state = 0, .external_lex_state = 2},
  [10] = {.lex_state = 0, .external_lex_state = 2},
  [11] = {.lex_state = 0, .external_lex_state = 2},
  [12] = {.lex_state = 0, .external_lex_state = 2},
  [13] = {.lex_state = 0, .external_lex_state = 3},
  [14] = {.lex_state = 0, .external_lex_state = 3},
  [15] = {.lex_state = 0, .external_lex_state = 3},
  [16] = {.lex_state = 0, .external_lex_state = 3},
  [17] = {.lex_state = 0, .external_lex_state = 3},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0, .external_lex_state = 2},
  [20] = {.lex_state = 0, .external_lex_state = 2},
  [21] = {.lex_state = 0, .external_lex_state = 4},
  [22] = {.lex_state = 0, .external_lex_state = 2},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0, .external_lex_state = 2},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0, .external_lex_state = 2},
  [27] = {.lex_state = 0, .external_lex_state = 2},
  [28] = {.lex_state = 0, .external_lex_state = 2},
  [29] = {.lex_state = 0, .external_lex_state = 2},
  [30] = {.lex_state = 0, .external_lex_state = 2},
  [31] = {.lex_state = 0, .external_lex_state = 2},
  [32] = {.lex_state = 0, .external_lex_state = 2},
  [33] = {.lex_state = 0, .external_lex_state = 4},
  [34] = {.lex_state = 0, .external_lex_state = 2},
  [35] = {.lex_state = 0, .external_lex_state = 4},
  [36] = {.lex_state = 0, .external_lex_state = 2},
  [37] = {.lex_state = 0, .external_lex_state = 2},
  [38] = {.lex_state = 0, .external_lex_state = 2},
  [39] = {.lex_state = 0, .external_lex_state = 3},
  [40] = {.lex_state = 0, .external_lex_state = 2},
  [41] = {.lex_state = 0, .external_lex_state = 5},
  [42] = {.lex_state = 0, .external_lex_state = 2},
  [43] = {.lex_state = 0, .external_lex_state = 4},
  [44] = {.lex_state = 0, .external_lex_state = 2},
  [45] = {.lex_state = 0, .external_lex_state = 4},
  [46] = {.lex_state = 0, .external_lex_state = 3},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0, .external_lex_state = 2},
  [50] = {.lex_state = 0, .external_lex_state = 6},
  [51] = {.lex_state = 0, .external_lex_state = 4},
  [52] = {.lex_state = 0, .external_lex_state = 7},
  [53] = {.lex_state = 0, .external_lex_state = 4},
  [54] = {.lex_state = 0, .external_lex_state = 4},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0, .external_lex_state = 4},
  [57] = {.lex_state = 0, .external_lex_state = 4},
  [58] = {.lex_state = 0, .external_lex_state = 4},
  [59] = {.lex_state = 0, .external_lex_state = 8},
  [60] = {.lex_state = 0, .external_lex_state = 4},
  [61] = {.lex_state = 0, .external_lex_state = 4},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0, .external_lex_state = 4},
  [65] = {.lex_state = 0, .external_lex_state = 9},
  [66] = {.lex_state = 0, .external_lex_state = 4},
  [67] = {.lex_state = 0, .external_lex_state = 6},
  [68] = {.lex_state = 0, .external_lex_state = 6},
  [69] = {.lex_state = 0, .external_lex_state = 6},
  [70] = {.lex_state = 0, .external_lex_state = 8},
  [71] = {.lex_state = 0, .external_lex_state = 10},
  [72] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [aux_sym_set_delimiter_statement_token1] = ACTIONS(3),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym__start_tag_name] = ACTIONS(1),
    [sym__end_tag_name] = ACTIONS(1),
    [sym__erroneous_end_tag_name] = ACTIONS(1),
    [sym_start_delimiter] = ACTIONS(1),
    [sym_end_delimiter] = ACTIONS(1),
    [sym__comment_content] = ACTIONS(1),
    [sym__identifier_content] = ACTIONS(1),
    [sym__set_start_delimiter_content] = ACTIONS(1),
    [sym__set_end_delimiter_content] = ACTIONS(1),
    [sym__old_end_delimiter] = ACTIONS(1),
    [sym_text] = ACTIONS(1),
  },
  [1] = {
    [sym_template] = STATE(55),
    [sym__declaration] = STATE(2),
    [sym_comment_statement] = STATE(2),
    [sym__statement] = STATE(2),
    [sym_interpolation_statement] = STATE(2),
    [sym_triple_statement] = STATE(2),
    [sym_ampersand_statement] = STATE(2),
    [sym_set_delimiter_statement] = STATE(2),
    [sym_partial_statement] = STATE(2),
    [sym_section] = STATE(2),
    [sym_section_begin] = STATE(4),
    [sym_inverted_section] = STATE(2),
    [sym_inverted_section_begin] = STATE(5),
    [sym_inheritance_statement] = STATE(2),
    [sym_inheritance_begin] = STATE(6),
    [sym_block_statement] = STATE(2),
    [sym_block_begin] = STATE(7),
    [aux_sym_template_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [aux_sym_set_delimiter_statement_token1] = ACTIONS(3),
    [sym_start_delimiter] = ACTIONS(7),
    [sym_text] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(7), 1,
      sym_start_delimiter,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    ACTIONS(13), 1,
      sym_text,
    STATE(4), 1,
      sym_section_begin,
    STATE(5), 1,
      sym_inverted_section_begin,
    STATE(6), 1,
      sym_inheritance_begin,
    STATE(7), 1,
      sym_block_begin,
    STATE(3), 13,
      sym__declaration,
      sym_comment_statement,
      sym__statement,
      sym_interpolation_statement,
      sym_triple_statement,
      sym_ampersand_statement,
      sym_set_delimiter_statement,
      sym_partial_statement,
      sym_section,
      sym_inverted_section,
      sym_inheritance_statement,
      sym_block_statement,
      aux_sym_template_repeat1,
  [40] = 9,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(17), 1,
      sym_start_delimiter,
    ACTIONS(20), 1,
      sym_text,
    STATE(4), 1,
      sym_section_begin,
    STATE(5), 1,
      sym_inverted_section_begin,
    STATE(6), 1,
      sym_inheritance_begin,
    STATE(7), 1,
      sym_block_begin,
    STATE(3), 13,
      sym__declaration,
      sym_comment_statement,
      sym__statement,
      sym_interpolation_statement,
      sym_triple_statement,
      sym_ampersand_statement,
      sym_set_delimiter_statement,
      sym_partial_statement,
      sym_section,
      sym_inverted_section,
      sym_inheritance_statement,
      sym_block_statement,
      aux_sym_template_repeat1,
  [80] = 9,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(23), 1,
      sym_start_delimiter,
    ACTIONS(25), 1,
      sym_text,
    STATE(4), 1,
      sym_section_begin,
    STATE(5), 1,
      sym_inverted_section_begin,
    STATE(6), 1,
      sym_inheritance_begin,
    STATE(7), 1,
      sym_block_begin,
    STATE(22), 1,
      sym__section_end,
    STATE(11), 11,
      sym__statement,
      sym_interpolation_statement,
      sym_triple_statement,
      sym_ampersand_statement,
      sym_set_delimiter_statement,
      sym_partial_statement,
      sym_section,
      sym_inverted_section,
      sym_inheritance_statement,
      sym_block_statement,
      aux_sym_section_repeat1,
  [118] = 9,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(23), 1,
      sym_start_delimiter,
    ACTIONS(27), 1,
      sym_text,
    STATE(4), 1,
      sym_section_begin,
    STATE(5), 1,
      sym_inverted_section_begin,
    STATE(6), 1,
      sym_inheritance_begin,
    STATE(7), 1,
      sym_block_begin,
    STATE(24), 1,
      sym__section_end,
    STATE(10), 11,
      sym__statement,
      sym_interpolation_statement,
      sym_triple_statement,
      sym_ampersand_statement,
      sym_set_delimiter_statement,
      sym_partial_statement,
      sym_section,
      sym_inverted_section,
      sym_inheritance_statement,
      sym_block_statement,
      aux_sym_section_repeat1,
  [156] = 9,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(23), 1,
      sym_start_delimiter,
    ACTIONS(29), 1,
      sym_text,
    STATE(4), 1,
      sym_section_begin,
    STATE(5), 1,
      sym_inverted_section_begin,
    STATE(6), 1,
      sym_inheritance_begin,
    STATE(7), 1,
      sym_block_begin,
    STATE(26), 1,
      sym__section_end,
    STATE(9), 11,
      sym__statement,
      sym_interpolation_statement,
      sym_triple_statement,
      sym_ampersand_statement,
      sym_set_delimiter_statement,
      sym_partial_statement,
      sym_section,
      sym_inverted_section,
      sym_inheritance_statement,
      sym_block_statement,
      aux_sym_section_repeat1,
  [194] = 9,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(23), 1,
      sym_start_delimiter,
    ACTIONS(31), 1,
      sym_text,
    STATE(4), 1,
      sym_section_begin,
    STATE(5), 1,
      sym_inverted_section_begin,
    STATE(6), 1,
      sym_inheritance_begin,
    STATE(7), 1,
      sym_block_begin,
    STATE(28), 1,
      sym__section_end,
    STATE(8), 11,
      sym__statement,
      sym_interpolation_statement,
      sym_triple_statement,
      sym_ampersand_statement,
      sym_set_delimiter_statement,
      sym_partial_statement,
      sym_section,
      sym_inverted_section,
      sym_inheritance_statement,
      sym_block_statement,
      aux_sym_section_repeat1,
  [232] = 9,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(23), 1,
      sym_start_delimiter,
    ACTIONS(33), 1,
      sym_text,
    STATE(4), 1,
      sym_section_begin,
    STATE(5), 1,
      sym_inverted_section_begin,
    STATE(6), 1,
      sym_inheritance_begin,
    STATE(7), 1,
      sym_block_begin,
    STATE(27), 1,
      sym__section_end,
    STATE(12), 11,
      sym__statement,
      sym_interpolation_statement,
      sym_triple_statement,
      sym_ampersand_statement,
      sym_set_delimiter_statement,
      sym_partial_statement,
      sym_section,
      sym_inverted_section,
      sym_inheritance_statement,
      sym_block_statement,
      aux_sym_section_repeat1,
  [270] = 9,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(23), 1,
      sym_start_delimiter,
    ACTIONS(33), 1,
      sym_text,
    STATE(4), 1,
      sym_section_begin,
    STATE(5), 1,
      sym_inverted_section_begin,
    STATE(6), 1,
      sym_inheritance_begin,
    STATE(7), 1,
      sym_block_begin,
    STATE(38), 1,
      sym__section_end,
    STATE(12), 11,
      sym__statement,
      sym_interpolation_statement,
      sym_triple_statement,
      sym_ampersand_statement,
      sym_set_delimiter_statement,
      sym_partial_statement,
      sym_section,
      sym_inverted_section,
      sym_inheritance_statement,
      sym_block_statement,
      aux_sym_section_repeat1,
  [308] = 9,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(23), 1,
      sym_start_delimiter,
    ACTIONS(33), 1,
      sym_text,
    STATE(4), 1,
      sym_section_begin,
    STATE(5), 1,
      sym_inverted_section_begin,
    STATE(6), 1,
      sym_inheritance_begin,
    STATE(7), 1,
      sym_block_begin,
    STATE(37), 1,
      sym__section_end,
    STATE(12), 11,
      sym__statement,
      sym_interpolation_statement,
      sym_triple_statement,
      sym_ampersand_statement,
      sym_set_delimiter_statement,
      sym_partial_statement,
      sym_section,
      sym_inverted_section,
      sym_inheritance_statement,
      sym_block_statement,
      aux_sym_section_repeat1,
  [346] = 9,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(23), 1,
      sym_start_delimiter,
    ACTIONS(33), 1,
      sym_text,
    STATE(4), 1,
      sym_section_begin,
    STATE(5), 1,
      sym_inverted_section_begin,
    STATE(6), 1,
      sym_inheritance_begin,
    STATE(7), 1,
      sym_block_begin,
    STATE(36), 1,
      sym__section_end,
    STATE(12), 11,
      sym__statement,
      sym_interpolation_statement,
      sym_triple_statement,
      sym_ampersand_statement,
      sym_set_delimiter_statement,
      sym_partial_statement,
      sym_section,
      sym_inverted_section,
      sym_inheritance_statement,
      sym_block_statement,
      aux_sym_section_repeat1,
  [384] = 8,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(35), 1,
      sym_start_delimiter,
    ACTIONS(38), 1,
      sym_text,
    STATE(4), 1,
      sym_section_begin,
    STATE(5), 1,
      sym_inverted_section_begin,
    STATE(6), 1,
      sym_inheritance_begin,
    STATE(7), 1,
      sym_block_begin,
    STATE(12), 11,
      sym__statement,
      sym_interpolation_statement,
      sym_triple_statement,
      sym_ampersand_statement,
      sym_set_delimiter_statement,
      sym_partial_statement,
      sym_section,
      sym_inverted_section,
      sym_inheritance_statement,
      sym_block_statement,
      aux_sym_section_repeat1,
  [419] = 14,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(41), 1,
      anon_sym_BANG,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    ACTIONS(45), 1,
      anon_sym_AMP,
    ACTIONS(47), 1,
      anon_sym_EQ,
    ACTIONS(49), 1,
      anon_sym_GT,
    ACTIONS(51), 1,
      anon_sym_POUND,
    ACTIONS(53), 1,
      anon_sym_CARET,
    ACTIONS(55), 1,
      anon_sym_LT,
    ACTIONS(57), 1,
      anon_sym_DOLLAR,
    ACTIONS(59), 1,
      anon_sym_DOT,
    ACTIONS(61), 1,
      sym__identifier_content,
    STATE(21), 1,
      sym_identifier,
    STATE(66), 2,
      sym__expression,
      sym_path_expression,
  [463] = 14,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    ACTIONS(45), 1,
      anon_sym_AMP,
    ACTIONS(47), 1,
      anon_sym_EQ,
    ACTIONS(49), 1,
      anon_sym_GT,
    ACTIONS(51), 1,
      anon_sym_POUND,
    ACTIONS(53), 1,
      anon_sym_CARET,
    ACTIONS(55), 1,
      anon_sym_LT,
    ACTIONS(57), 1,
      anon_sym_DOLLAR,
    ACTIONS(59), 1,
      anon_sym_DOT,
    ACTIONS(61), 1,
      sym__identifier_content,
    ACTIONS(63), 1,
      anon_sym_SLASH,
    STATE(21), 1,
      sym_identifier,
    STATE(66), 2,
      sym__expression,
      sym_path_expression,
  [507] = 13,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    ACTIONS(45), 1,
      anon_sym_AMP,
    ACTIONS(47), 1,
      anon_sym_EQ,
    ACTIONS(49), 1,
      anon_sym_GT,
    ACTIONS(51), 1,
      anon_sym_POUND,
    ACTIONS(53), 1,
      anon_sym_CARET,
    ACTIONS(55), 1,
      anon_sym_LT,
    ACTIONS(57), 1,
      anon_sym_DOLLAR,
    ACTIONS(59), 1,
      anon_sym_DOT,
    ACTIONS(61), 1,
      sym__identifier_content,
    STATE(21), 1,
      sym_identifier,
    STATE(66), 2,
      sym__expression,
      sym_path_expression,
  [548] = 5,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(61), 1,
      sym__identifier_content,
    ACTIONS(65), 1,
      anon_sym_DOT,
    STATE(21), 1,
      sym_identifier,
    STATE(51), 2,
      sym__expression,
      sym_path_expression,
  [565] = 5,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(67), 1,
      anon_sym_DOT,
    ACTIONS(69), 1,
      sym__identifier_content,
    STATE(25), 1,
      sym_identifier,
    STATE(62), 2,
      sym__expression,
      sym_path_expression,
  [582] = 4,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(71), 1,
      anon_sym_RBRACE,
    ACTIONS(73), 1,
      anon_sym_DOT,
    STATE(23), 1,
      aux_sym_path_expression_repeat1,
  [595] = 2,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(75), 3,
      sym_start_delimiter,
      sym_text,
      ts_builtin_sym_end,
  [604] = 2,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(77), 3,
      sym_start_delimiter,
      sym_text,
      ts_builtin_sym_end,
  [613] = 4,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(79), 1,
      anon_sym_DOT,
    ACTIONS(81), 1,
      sym_end_delimiter,
    STATE(35), 1,
      aux_sym_path_expression_repeat1,
  [626] = 2,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(83), 3,
      sym_start_delimiter,
      sym_text,
      ts_builtin_sym_end,
  [635] = 4,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(85), 1,
      anon_sym_RBRACE,
    ACTIONS(87), 1,
      anon_sym_DOT,
    STATE(23), 1,
      aux_sym_path_expression_repeat1,
  [648] = 2,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(90), 3,
      sym_start_delimiter,
      sym_text,
      ts_builtin_sym_end,
  [657] = 4,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(73), 1,
      anon_sym_DOT,
    ACTIONS(81), 1,
      anon_sym_RBRACE,
    STATE(18), 1,
      aux_sym_path_expression_repeat1,
  [670] = 2,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(92), 3,
      sym_start_delimiter,
      sym_text,
      ts_builtin_sym_end,
  [679] = 2,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(94), 3,
      sym_start_delimiter,
      sym_text,
      ts_builtin_sym_end,
  [688] = 2,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(96), 3,
      sym_start_delimiter,
      sym_text,
      ts_builtin_sym_end,
  [697] = 2,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(98), 3,
      sym_start_delimiter,
      sym_text,
      ts_builtin_sym_end,
  [706] = 2,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(100), 3,
      sym_start_delimiter,
      sym_text,
      ts_builtin_sym_end,
  [715] = 2,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(102), 3,
      sym_start_delimiter,
      sym_text,
      ts_builtin_sym_end,
  [724] = 2,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(104), 3,
      sym_start_delimiter,
      sym_text,
      ts_builtin_sym_end,
  [733] = 4,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(85), 1,
      sym_end_delimiter,
    ACTIONS(106), 1,
      anon_sym_DOT,
    STATE(33), 1,
      aux_sym_path_expression_repeat1,
  [746] = 2,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(109), 3,
      sym_start_delimiter,
      sym_text,
      ts_builtin_sym_end,
  [755] = 4,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(71), 1,
      sym_end_delimiter,
    ACTIONS(79), 1,
      anon_sym_DOT,
    STATE(33), 1,
      aux_sym_path_expression_repeat1,
  [768] = 2,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(111), 3,
      sym_start_delimiter,
      sym_text,
      ts_builtin_sym_end,
  [777] = 2,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(113), 3,
      sym_start_delimiter,
      sym_text,
      ts_builtin_sym_end,
  [786] = 2,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(115), 3,
      sym_start_delimiter,
      sym_text,
      ts_builtin_sym_end,
  [795] = 3,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(69), 1,
      sym__identifier_content,
    STATE(48), 1,
      sym_identifier,
  [805] = 2,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(117), 2,
      sym_start_delimiter,
      sym_text,
  [813] = 2,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(119), 2,
      sym__end_tag_name,
      sym__erroneous_end_tag_name,
  [821] = 2,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(121), 2,
      sym_start_delimiter,
      sym_text,
  [829] = 2,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(123), 2,
      sym_end_delimiter,
      anon_sym_DOT,
  [837] = 2,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(125), 2,
      sym_start_delimiter,
      sym_text,
  [845] = 2,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(85), 2,
      sym_end_delimiter,
      anon_sym_DOT,
  [853] = 3,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(61), 1,
      sym__identifier_content,
    STATE(45), 1,
      sym_identifier,
  [863] = 2,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(123), 2,
      anon_sym_RBRACE,
      anon_sym_DOT,
  [871] = 2,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(85), 2,
      anon_sym_RBRACE,
      anon_sym_DOT,
  [879] = 2,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(127), 2,
      sym_start_delimiter,
      sym_text,
  [887] = 2,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(129), 1,
      sym__start_tag_name,
  [894] = 2,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(131), 1,
      sym_end_delimiter,
  [901] = 2,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(133), 1,
      sym__set_end_delimiter_content,
  [908] = 2,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(135), 1,
      sym_end_delimiter,
  [915] = 2,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(137), 1,
      sym_end_delimiter,
  [922] = 2,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(139), 1,
      ts_builtin_sym_end,
  [929] = 2,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(141), 1,
      sym_end_delimiter,
  [936] = 2,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(143), 1,
      sym_end_delimiter,
  [943] = 2,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(145), 1,
      sym_end_delimiter,
  [950] = 2,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(147), 1,
      sym__comment_content,
  [957] = 2,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(149), 1,
      sym_end_delimiter,
  [964] = 2,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(151), 1,
      sym_end_delimiter,
  [971] = 2,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(153), 1,
      anon_sym_RBRACE,
  [978] = 2,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(155), 1,
      anon_sym_EQ,
  [985] = 2,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(157), 1,
      sym_end_delimiter,
  [992] = 2,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(159), 1,
      sym__old_end_delimiter,
  [999] = 2,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(161), 1,
      sym_end_delimiter,
  [1006] = 2,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(163), 1,
      sym__start_tag_name,
  [1013] = 2,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(165), 1,
      sym__start_tag_name,
  [1020] = 2,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(167), 1,
      sym__start_tag_name,
  [1027] = 2,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(169), 1,
      sym__comment_content,
  [1034] = 2,
    ACTIONS(3), 1,
      aux_sym_set_delimiter_statement_token1,
    ACTIONS(171), 1,
      sym__set_start_delimiter_content,
  [1041] = 1,
    ACTIONS(173), 1,
      aux_sym_set_delimiter_statement_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 40,
  [SMALL_STATE(4)] = 80,
  [SMALL_STATE(5)] = 118,
  [SMALL_STATE(6)] = 156,
  [SMALL_STATE(7)] = 194,
  [SMALL_STATE(8)] = 232,
  [SMALL_STATE(9)] = 270,
  [SMALL_STATE(10)] = 308,
  [SMALL_STATE(11)] = 346,
  [SMALL_STATE(12)] = 384,
  [SMALL_STATE(13)] = 419,
  [SMALL_STATE(14)] = 463,
  [SMALL_STATE(15)] = 507,
  [SMALL_STATE(16)] = 548,
  [SMALL_STATE(17)] = 565,
  [SMALL_STATE(18)] = 582,
  [SMALL_STATE(19)] = 595,
  [SMALL_STATE(20)] = 604,
  [SMALL_STATE(21)] = 613,
  [SMALL_STATE(22)] = 626,
  [SMALL_STATE(23)] = 635,
  [SMALL_STATE(24)] = 648,
  [SMALL_STATE(25)] = 657,
  [SMALL_STATE(26)] = 670,
  [SMALL_STATE(27)] = 679,
  [SMALL_STATE(28)] = 688,
  [SMALL_STATE(29)] = 697,
  [SMALL_STATE(30)] = 706,
  [SMALL_STATE(31)] = 715,
  [SMALL_STATE(32)] = 724,
  [SMALL_STATE(33)] = 733,
  [SMALL_STATE(34)] = 746,
  [SMALL_STATE(35)] = 755,
  [SMALL_STATE(36)] = 768,
  [SMALL_STATE(37)] = 777,
  [SMALL_STATE(38)] = 786,
  [SMALL_STATE(39)] = 795,
  [SMALL_STATE(40)] = 805,
  [SMALL_STATE(41)] = 813,
  [SMALL_STATE(42)] = 821,
  [SMALL_STATE(43)] = 829,
  [SMALL_STATE(44)] = 837,
  [SMALL_STATE(45)] = 845,
  [SMALL_STATE(46)] = 853,
  [SMALL_STATE(47)] = 863,
  [SMALL_STATE(48)] = 871,
  [SMALL_STATE(49)] = 879,
  [SMALL_STATE(50)] = 887,
  [SMALL_STATE(51)] = 894,
  [SMALL_STATE(52)] = 901,
  [SMALL_STATE(53)] = 908,
  [SMALL_STATE(54)] = 915,
  [SMALL_STATE(55)] = 922,
  [SMALL_STATE(56)] = 929,
  [SMALL_STATE(57)] = 936,
  [SMALL_STATE(58)] = 943,
  [SMALL_STATE(59)] = 950,
  [SMALL_STATE(60)] = 957,
  [SMALL_STATE(61)] = 964,
  [SMALL_STATE(62)] = 971,
  [SMALL_STATE(63)] = 978,
  [SMALL_STATE(64)] = 985,
  [SMALL_STATE(65)] = 992,
  [SMALL_STATE(66)] = 999,
  [SMALL_STATE(67)] = 1006,
  [SMALL_STATE(68)] = 1013,
  [SMALL_STATE(69)] = 1020,
  [SMALL_STATE(70)] = 1027,
  [SMALL_STATE(71)] = 1034,
  [SMALL_STATE(72)] = 1041,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0),
  [17] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [20] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path_expression, 2, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set_delimiter_statement, 7, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__section_end, 4, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_path_expression_repeat1, 2, 0, 0),
  [87] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_path_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inverted_section, 2, 0, 1),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inheritance_statement, 2, 0, 2),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_statement, 3, 0, 6),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_statement, 2, 0, 3),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ampersand_statement, 4, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_partial_statement, 4, 0, 8),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_triple_statement, 5, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment_statement, 4, 0, 7),
  [106] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_path_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpolation_statement, 3, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 3, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inverted_section, 3, 0, 4),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inheritance_statement, 3, 0, 5),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_begin, 4, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inheritance_begin, 4, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inverted_section_begin, 4, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_begin, 4, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [139] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__start_tag_name = 0,
  ts_external_token__end_tag_name = 1,
  ts_external_token__erroneous_end_tag_name = 2,
  ts_external_token_start_delimiter = 3,
  ts_external_token_end_delimiter = 4,
  ts_external_token__comment_content = 5,
  ts_external_token__identifier_content = 6,
  ts_external_token__set_start_delimiter_content = 7,
  ts_external_token__set_end_delimiter_content = 8,
  ts_external_token__old_end_delimiter = 9,
  ts_external_token_text = 10,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__start_tag_name] = sym__start_tag_name,
  [ts_external_token__end_tag_name] = sym__end_tag_name,
  [ts_external_token__erroneous_end_tag_name] = sym__erroneous_end_tag_name,
  [ts_external_token_start_delimiter] = sym_start_delimiter,
  [ts_external_token_end_delimiter] = sym_end_delimiter,
  [ts_external_token__comment_content] = sym__comment_content,
  [ts_external_token__identifier_content] = sym__identifier_content,
  [ts_external_token__set_start_delimiter_content] = sym__set_start_delimiter_content,
  [ts_external_token__set_end_delimiter_content] = sym__set_end_delimiter_content,
  [ts_external_token__old_end_delimiter] = sym__old_end_delimiter,
  [ts_external_token_text] = sym_text,
};

static const bool ts_external_scanner_states[11][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__start_tag_name] = true,
    [ts_external_token__end_tag_name] = true,
    [ts_external_token__erroneous_end_tag_name] = true,
    [ts_external_token_start_delimiter] = true,
    [ts_external_token_end_delimiter] = true,
    [ts_external_token__comment_content] = true,
    [ts_external_token__identifier_content] = true,
    [ts_external_token__set_start_delimiter_content] = true,
    [ts_external_token__set_end_delimiter_content] = true,
    [ts_external_token__old_end_delimiter] = true,
    [ts_external_token_text] = true,
  },
  [2] = {
    [ts_external_token_start_delimiter] = true,
    [ts_external_token_text] = true,
  },
  [3] = {
    [ts_external_token__identifier_content] = true,
  },
  [4] = {
    [ts_external_token_end_delimiter] = true,
  },
  [5] = {
    [ts_external_token__end_tag_name] = true,
    [ts_external_token__erroneous_end_tag_name] = true,
  },
  [6] = {
    [ts_external_token__start_tag_name] = true,
  },
  [7] = {
    [ts_external_token__set_end_delimiter_content] = true,
  },
  [8] = {
    [ts_external_token__comment_content] = true,
  },
  [9] = {
    [ts_external_token__old_end_delimiter] = true,
  },
  [10] = {
    [ts_external_token__set_start_delimiter_content] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_mustache_external_scanner_create(void);
void tree_sitter_mustache_external_scanner_destroy(void *);
bool tree_sitter_mustache_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_mustache_external_scanner_serialize(void *, char *);
void tree_sitter_mustache_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_mustache(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_mustache_external_scanner_create,
      tree_sitter_mustache_external_scanner_destroy,
      tree_sitter_mustache_external_scanner_scan,
      tree_sitter_mustache_external_scanner_serialize,
      tree_sitter_mustache_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
